import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { isTenantScoped, loadEffectivePolicies } from "./policyParser";

/**
 * Clinical governance, consent, identity, credentialing and readiness gate.
 *
 * Proves from the migrations that separation of duties, self-approval denial,
 * immutability of approved versions, consent applicability/withdrawal, identity
 * data minimization, credential expiry handling, access revocation, PHI-minimized
 * support and fail-closed launch readiness are enforced in the database.
 */
const MIGRATIONS = path.resolve(process.cwd(), "supabase/migrations");
const sql = readdirSync(MIGRATIONS)
  .filter((f) => f.endsWith(".sql"))
  .sort()
  .map((f) => readFileSync(path.join(MIGRATIONS, f), "utf8"))
  .join("\n");

const policies = loadEffectivePolicies();
const TABLES = [
  "governance_roles",
  "clinical_protocols",
  "consent_documents",
  "governance_approvals",
  "consent_records",
  "identity_verification_profiles",
  "identity_verifications",
  "staff_credentials",
  "access_attestations",
  "support_cases",
  "incident_reports",
  "complaints",
  "continuity_exercises",
  "vendor_agreements",
  "workforce_training",
  "launch_readiness_gates",
] as const;

describe("governance tenancy", () => {
  it.each(TABLES)("%s: every policy is tenant-scoped or role-gated", (table) => {
    const list = policies.get(table) ?? [];
    expect(list.length).toBeGreaterThan(0);
    for (const p of list) {
      const ok = isTenantScoped(p.expr) || /has_(role|governance_role)\(/i.test(p.expr);
      expect(ok, `${table} · ${p.name} is not tenant-scoped`).toBe(true);
    }
  });

  it.each(TABLES)("%s: no anonymous or public access", (table) => {
    expect(sql).not.toMatch(new RegExp(`GRANT[^;]*ON\\s+public\\.${table}\\s+TO\\s+(anon|public)`, "i"));
    expect(sql).not.toMatch(new RegExp(`ON\\s+public\\.${table}\\s+FOR\\s+\\w+\\s+TO\\s+anon`, "i"));
  });
});

describe("separation of duties", () => {
  it("authors cannot approve their own clinical content", () => {
    expect(sql).toMatch(/authors cannot approve their own clinical content/i);
  });

  it("one person cannot supply both required approvals", () => {
    expect(sql).toMatch(/separation of duties: one person cannot supply both approvals/i);
  });

  it("approvers must hold the governance role at the artifact facility", () => {
    expect(sql).toMatch(/approver does not hold the % role at this facility/i);
    expect(sql).toMatch(/an approval must stay inside the artifact facility/i);
  });

  it("production use requires a medical director plus independent compliance approval", () => {
    expect(sql).toMatch(/production use requires a medical-director approval and an independent compliance approval/i);
  });

  it("an approval rationale is mandatory and approvals are append-only", () => {
    expect(sql).toMatch(/an approval rationale is required/i);
    expect(sql).toMatch(/CREATE TRIGGER governance_approvals_append_only[\s\S]*?deny_mutation/i);
    const list = policies.get("governance_approvals") ?? [];
    expect(list.filter((p) => p.cmd === "UPDATE" || p.cmd === "DELETE" || p.cmd === "ALL")).toHaveLength(0);
  });
});

describe("immutable approved versions", () => {
  it("approved versions can only be retired or superseded", () => {
    expect(sql).toMatch(/approved versions are immutable; publish a new version/i);
    expect(sql).toMatch(/approved versions may only be retired; publish a new version/i);
    expect(sql).toMatch(/a superseding version must increment the version number/i);
    expect(sql).toMatch(/a change summary is required when superseding a version/i);
  });

  it("illegal governance transitions are rejected", () => {
    expect(sql).toMatch(/illegal governance transition/i);
  });

  it("autogenerated content can never approve or override a safety rule", () => {
    expect(sql).toMatch(/autogenerated clinical content cannot approve or override a safety rule/i);
  });

  it("evidence is required before approval and clients cannot delete versions", () => {
    expect(sql).toMatch(/an evidence or source reference is required before approval/i);
    expect(sql).toMatch(/CREATE TRIGGER clinical_protocols_no_client_delete/i);
    expect(sql).toMatch(/CREATE TRIGGER consent_documents_no_client_delete/i);
  });
});

describe("consent applicability and withdrawal", () => {
  it("only approved consent versions may be presented, inside the facility", () => {
    expect(sql).toMatch(/only an approved consent version can be presented to a patient/i);
    expect(sql).toMatch(/consent document must belong to this facility/i);
    expect(sql).toMatch(/patient does not belong to this facility/i);
  });

  it("consent evidence is immutable and withdrawal is irreversible", () => {
    expect(sql).toMatch(/consent evidence hash is required/i);
    expect(sql).toMatch(/consent evidence is immutable/i);
    expect(sql).toMatch(/a consent withdrawal cannot be reversed/i);
    expect(sql).toMatch(/a withdrawal reason is required/i);
    expect(sql).toMatch(/CREATE TRIGGER consent_records_no_client_delete/i);
  });
});

describe("identity data minimization", () => {
  it("credential payloads, biometrics and images are rejected", () => {
    expect(sql).toMatch(/identity verification stores metadata only/i);
    expect(sql).toMatch(/identity reference is a vendor reference, not a credential payload/i);
  });

  it("verifications are append-only and require a facility-owned subject", () => {
    expect(sql).toMatch(/CREATE TRIGGER identity_verifications_append_only[\s\S]*?deny_mutation/i);
    expect(sql).toMatch(/a patient verification requires a patient/i);
    expect(sql).toMatch(/a staff verification requires a subject user/i);
    expect(sql).toMatch(/a manual identity exception requires a reviewer and a documented reason/i);
  });
});

describe("credentialing and access lifecycle", () => {
  it("credential records store metadata only and require primary-source evidence", () => {
    expect(sql).toMatch(/credentialing records store status and dates only, never credential values/i);
    expect(sql).toMatch(/primary-source verification evidence is required to mark a credential verified/i);
    expect(sql).toMatch(/CREATE TRIGGER staff_credentials_no_client_delete/i);
  });

  it("attestations are append-only and terminations revoke access", () => {
    expect(sql).toMatch(/CREATE TRIGGER access_attestations_append_only[\s\S]*?deny_mutation/i);
    expect(sql).toMatch(/CREATE TRIGGER apply_access_attestation AFTER INSERT ON public\.access_attestations/i);
  });
});

describe("support PHI minimization", () => {
  it("identifier patterns and oversized descriptions are rejected", () => {
    expect(sql).toMatch(/support cases are PHI-minimized/i);
    expect(sql).toMatch(/support description exceeds the 2000 character limit/i);
    expect(sql).toMatch(/referenced patient does not belong to this facility/i);
  });
});

describe("launch readiness fails closed", () => {
  it("readiness is calculated server-side across internal and external gates", () => {
    expect(sql).toMatch(/CREATE OR REPLACE FUNCTION public\.launch_readiness/i);
    for (const gate of ["licensure", "clinical_protocol", "safety_screen", "consent",
      "identity_proofing", "vendor_baa", "credentialing"]) {
      expect(sql, `missing gate ${gate}`).toMatch(new RegExp(`'${gate}'`));
    }
  });

  it("readiness is denied outside the caller's facility", () => {
    expect(sql).toMatch(/IF NOT public\.is_my_hospital\(p_hospital_id\) THEN[\s\S]*?'authorized', false/i);
  });

  it("state availability cannot be published while a gate is unverified", () => {
    expect(sql).toMatch(/CREATE TRIGGER gate_state_service_availability/i);
  });

  it("privileged governance helpers are not callable anonymously", () => {
    expect(sql).toMatch(/REVOKE ALL ON FUNCTION public\.has_governance_role\(uuid, uuid, text\) FROM PUBLIC, anon/i);
    expect(sql).toMatch(/REVOKE ALL ON FUNCTION public\.apply_access_attestation\(\) FROM PUBLIC, anon, authenticated/i);
  });
});
