
-- Create patient_vitals table for dynamic insights and trends
CREATE TABLE public.patient_vitals (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  insights JSONB NOT NULL DEFAULT '[]'::jsonb,
  trends JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(patient_id)
);

ALTER TABLE public.patient_vitals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Clinicians can view patient vitals"
ON public.patient_vitals FOR SELECT
USING (has_role(auth.uid(), 'clinician'::app_role) OR has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can manage patient vitals"
ON public.patient_vitals FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role));

-- Trigger for updated_at
CREATE TRIGGER update_patient_vitals_updated_at
BEFORE UPDATE ON public.patient_vitals
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- =============================================
-- SEED CLINICAL NOTES for all 23 patients
-- =============================================

-- Memorial General Hospital (Epic) patients
-- Robert Chen (ICU, Sepsis) - 2887cfc2
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('2887cfc2-9a39-49e2-b838-01c1e0463b51', 'progress', 'signed', '{"subjective":"Patient reports persistent fever, chills, and malaise. Complains of diffuse abdominal pain. Denies chest pain or dyspnea.","objective":"T 39.1°C, HR 112, BP 88/52 on levophed 0.08 mcg/kg/min, RR 22, SpO2 94% on 4L NC. WBC 18.2, Lactate 4.1 → 2.8 after 2L NS bolus. Blood cultures x2 drawn. CT abdomen shows possible cholangitis. Procalcitonin 12.4.","assessment":"Severe sepsis secondary to acute cholangitis. Hemodynamically unstable requiring vasopressor support. Lactate trending down with fluid resuscitation.","plan":"1. Continue norepinephrine, target MAP >65\n2. Meropenem 1g IV q8h (day 2)\n3. GI consult for possible ERCP\n4. Repeat lactate q4h\n5. Central line placement for vasopressor management\n6. Strict I/O monitoring"}', now() - interval '1 day'),
('2887cfc2-9a39-49e2-b838-01c1e0463b51', 'progress', 'draft', '{"subjective":"Patient slightly more alert this morning. Still febrile but reports less abdominal pain. Tolerating clear liquids.","objective":"T 38.4°C (trending down), HR 98, BP 102/64 (weaned off vasopressors 0400), RR 18, SpO2 96% on 2L NC. WBC 14.1 (↓ from 18.2). Lactate 1.8 (normalized). Blood cultures: Gram-negative rods in 2/2 bottles.","assessment":"Sepsis improving. Successfully weaned off vasopressors. Culture data pending speciation. Cholangitis as likely source.","plan":"1. Continue meropenem, narrow based on sensitivities\n2. ERCP scheduled for tomorrow AM\n3. Advance diet as tolerated\n4. Remove arterial line if stable x12h\n5. PT/OT evaluation for mobilization"}', now()),
('2887cfc2-9a39-49e2-b838-01c1e0463b51', 'consult', 'signed', '{"subjective":"GI consult requested for cholangitis management and ERCP planning.","objective":"CT abdomen: dilated common bile duct to 12mm with intrahepatic ductal dilation. No discrete mass. Gallbladder distended with pericholecystic fluid. Labs: Total bilirubin 4.2, direct 3.1, ALP 342, GGT 285.","assessment":"Acute cholangitis with biliary obstruction. Likely choledocholithiasis given absence of mass on CT. Tokyo criteria: Grade III (organ dysfunction).","plan":"1. ERCP with sphincterotomy and stone extraction scheduled\n2. If ERCP fails, percutaneous transhepatic biliary drainage\n3. Cholecystectomy after acute episode resolves\n4. Continue broad-spectrum antibiotics"}', now() - interval '12 hours');

-- Maria Santos (ICU, STEMI) - 77f4db2e
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('77f4db2e-9d3b-47aa-8d56-71e84129b300', 'progress', 'signed', '{"subjective":"Patient reports substernal chest pressure began 2 hours prior to arrival. Radiating to left arm. Associated diaphoresis and nausea. Pain 8/10 at presentation, now 2/10 post-intervention.","objective":"ECG: ST elevation V1-V4 with reciprocal changes in II, III, aVF. Troponin I: 12.4 ng/mL (↑). Echo: EF 35%, anterior wall akinesis. Cath: 100% occlusion of LAD, successful PCI with DES placement. TIMI 3 flow restored. Door-to-balloon: 62 minutes.","assessment":"Acute anterior STEMI with successful primary PCI to LAD. Reduced EF 35% with regional wall motion abnormality. Cardiogenic shock not present.","plan":"1. DAPT: Aspirin 81mg + Ticagrelor 90mg BID\n2. Heparin gtt per ACS protocol\n3. Metoprolol 12.5mg PO BID (hold if HR <55 or SBP <100)\n4. Atorvastatin 80mg daily\n5. Serial troponins q6h\n6. Repeat echo in 48-72h\n7. Cardiac rehab referral"}', now() - interval '1 day'),
('77f4db2e-9d3b-47aa-8d56-71e84129b300', 'progress', 'draft', '{"subjective":"No recurrent chest pain. Mild fatigue. Tolerated ambulation to bathroom with assistance. No orthopnea or PND.","objective":"HR 72 (NSR), BP 118/72, RR 16, SpO2 98% RA. Troponin trending: 12.4 → 8.2 → 4.1 (down-trending). No new ST changes. Lungs clear. JVP not elevated. Groin access site: clean, no hematoma. Pedal pulses 2+ bilaterally.","assessment":"STEMI day 2. Hemodynamically stable post-PCI. Troponins down-trending as expected. No signs of heart failure.","plan":"1. Continue DAPT and statin\n2. Start ACE inhibitor (Lisinopril 2.5mg) today\n3. Advance activity as tolerated\n4. Echocardiogram repeat tomorrow\n5. HbA1c and lipid panel if not done\n6. Smoking cessation counseling\n7. Anticipated transfer to step-down unit today"}', now());

-- Richard Moore (ICU, Respiratory Failure) - c899d27a
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('c899d27a-4069-4f15-bcc6-ff1c4a55cb5f', 'progress', 'signed', '{"subjective":"Patient intubated, unable to provide history. Per family: progressive dyspnea x3 days, productive cough with yellow sputum, fever at home.","objective":"Ventilator: AC/VC, TV 450, RR 18, PEEP 10, FiO2 60%. ABG: 7.32/48/78/24. P/F ratio 130. CXR: bilateral infiltrates R>L. WBC 22.1, Procalcitonin 8.7. Sputum culture pending. APACHE II score: 24.","assessment":"Acute hypoxemic respiratory failure secondary to severe community-acquired pneumonia. Meeting ARDS criteria (P/F <150). High severity of illness.","plan":"1. Lung-protective ventilation strategy\n2. Prone positioning if P/F <150 on next ABG\n3. Piperacillin-tazobactam + Azithromycin\n4. Legionella and pneumococcal urine antigens\n5. Daily SBTs when FiO2 ≤40% and PEEP ≤8\n6. DVT prophylaxis with heparin SQ\n7. Stress ulcer prophylaxis\n8. Nutrition: start enteral feeds via OG tube"}', now() - interval '2 days'),
('c899d27a-4069-4f15-bcc6-ff1c4a55cb5f', 'progress', 'draft', '{"subjective":"Sedation lightened. Patient following commands intermittently. Cough reflex present.","objective":"Vent: AC/VC, TV 450, RR 14, PEEP 8, FiO2 40%. ABG: 7.38/42/92/25. P/F ratio 230 (improved). CXR: interval improvement bilateral infiltrates. WBC 15.3 (↓). Temp 37.8°C. Sputum cx: Streptococcus pneumoniae, sensitive to penicillin.","assessment":"Improving ARDS/pneumonia. P/F ratio improved significantly. Culture-directed therapy appropriate.","plan":"1. Narrow antibiotics to ampicillin-sulbactam\n2. SBT trial today — PS 5/5\n3. If passes SBT, plan extubation tomorrow AM\n4. Continue DVT and stress ulcer prophylaxis\n5. PT at bedside when extubated\n6. Family meeting re: progress and plan"}', now());

-- William Thompson (Med-Surg, CHF) - 7ddc5fc4
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('7ddc5fc4-597d-42ce-b0db-53ff7391eab8', 'progress', 'signed', '{"subjective":"Patient reports 3-pillow orthopnea, PND x2 nights, and 10-lb weight gain over 2 weeks. Lower extremity swelling bilateral. Compliance with medications has been poor — ran out of furosemide 1 week ago.","objective":"BP 158/92, HR 96, RR 22, SpO2 91% on 2L NC. Weight 98kg (baseline 89kg). JVP elevated to ear. Bibasilar crackles to mid-lung fields. 3+ pitting edema bilateral LE to knees. BNP 1842 pg/mL. Cr 1.6 (baseline 1.1). CXR: bilateral pleural effusions, pulmonary edema.","assessment":"Acute decompensated heart failure (HFrEF, EF 25%) with volume overload due to medication non-compliance. AKI likely pre-renal/cardiorenal.","plan":"1. IV furosemide 40mg BID with strict I/O\n2. Daily weights\n3. Fluid restriction 1.5L/day\n4. Restart home medications: carvedilol 12.5mg BID, lisinopril 10mg daily\n5. Renal function monitoring q12h\n6. Dietary counseling — low sodium\n7. Social work consult for medication access"}', now() - interval '1 day'),
('7ddc5fc4-597d-42ce-b0db-53ff7391eab8', 'progress', 'draft', '{"subjective":"Breathing much better today. Slept flat for first time in weeks. Good urine output overnight.","objective":"BP 132/78, HR 82, RR 16, SpO2 96% RA. Weight 95kg (↓3kg). Net negative 2.1L over 24h. Crackles at bases only. Edema 2+ (improved). BNP 1240 (↓). Cr 1.4 (↓). UOP 1.8L/24h.","assessment":"CHF exacerbation responding well to IV diuresis. Weight trending toward dry weight. Renal function improving.","plan":"1. Continue IV furosemide, target net negative 1-1.5L/day\n2. When euvolemic, convert to PO furosemide\n3. Advance activity — chair sitting, ambulation with PT\n4. Pharmacy consult for discharge med management\n5. Heart failure education by nursing\n6. Target discharge in 2-3 days if stable on PO diuretics"}', now());

-- Dorothy Williams (Med-Surg, Pneumonia) - 2af62d29
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('2af62d29-02ee-44f5-b708-f4c8290de779', 'progress', 'signed', '{"subjective":"Patient is an 81-year-old female presenting with 3 days of cough, fever, and mild confusion. Daughter notes she has been less active and eating poorly.","objective":"T 38.6°C, HR 88, BP 126/74, RR 20, SpO2 93% on RA. CXR: right lower lobe consolidation. WBC 13.8. Procalcitonin 2.1. UA negative. BMP: Na 134, K 3.8, Cr 0.9. CURB-65 score: 2.","assessment":"Community-acquired pneumonia, moderate severity. Mild hyponatremia likely SIADH vs. dehydration. Age-related risk factors for complications.","plan":"1. Ceftriaxone 1g IV daily + Azithromycin 500mg IV daily\n2. IV fluids: D5 1/2NS at 75 mL/hr\n3. Incentive spirometry q1h while awake\n4. Fall precautions\n5. Repeat CXR in 48h\n6. If improving, transition to PO antibiotics and plan discharge"}', now() - interval '2 days');

-- Barbara Taylor (Med-Surg, Post-op hip) - 374cb9a1
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('374cb9a1-0e4b-4655-b867-ac14e996f3cd', 'progress', 'signed', '{"subjective":"POD 1 from right total hip arthroplasty. Patient reports moderate surgical site pain (5/10) well-controlled with current regimen. Nausea resolved. Ambulated with PT this morning with rolling walker.","objective":"T 37.2°C, HR 78, BP 134/82, SpO2 97% RA. Surgical site: clean, dry, intact. Drain output 120mL serosanguinous. Hgb 9.8 (pre-op 12.1). Sensation intact distally. DP/PT pulses 2+. No calf tenderness.","assessment":"Status post R THA, recovering appropriately. Expected post-op anemia. Good early mobilization.","plan":"1. Continue multimodal pain management\n2. DVT prophylaxis: enoxaparin 40mg SQ daily\n3. PT BID — weight-bearing as tolerated\n4. Remove drain when output <30mL/shift\n5. Transfuse if Hgb <7 or symptomatic\n6. Anticipated discharge POD 2-3 to rehab"}', now() - interval '12 hours'),
('374cb9a1-0e4b-4655-b867-ac14e996f3cd', 'progress', 'draft', '{"subjective":"Pain improved to 3/10. Walked 150 feet with rolling walker. Appetite returning.","objective":"Afebrile. Vitals stable. Drain output 25mL (↓). Hgb 9.4 (stable). Wound clean. Ambulating independently with walker x2 sessions.","assessment":"Excellent post-op recovery. Meeting PT milestones. Ready for drain removal and discharge planning.","plan":"1. Remove surgical drain today\n2. Transition to oral pain medications\n3. Discharge to rehab facility tomorrow if PT clears\n4. Continue DVT prophylaxis x4 weeks post-op\n5. Follow-up orthopedics in 2 weeks"}', now());

-- James Anderson (Cardiac, Afib) - 4f8084f1
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('4f8084f1-18bb-4bb4-8804-bde640f7c574', 'progress', 'signed', '{"subjective":"Patient presents with 2 days of palpitations and intermittent dizziness. Denies syncope, chest pain, or dyspnea. Reports increased caffeine intake and poor sleep recently.","objective":"HR 142 (irregularly irregular), BP 138/88, RR 18, SpO2 97% RA. ECG: Atrial fibrillation with rapid ventricular response (RVR), no ST changes. TSH normal. K 3.6. Mg 1.7. Echo: EF 50%, no valvular disease, LA mildly dilated.","assessment":"New-onset atrial fibrillation with RVR. CHA₂DS₂-VASc score: 3. HAS-BLED score: 1. No structural heart disease on echo.","plan":"1. Rate control: Diltiazem 30mg IV bolus, then 10mg/hr drip\n2. Target HR <110\n3. Replete K >4.0 and Mg >2.0\n4. Initiate anticoagulation: Apixaban 5mg BID\n5. Cardiology consult for rhythm vs rate control strategy\n6. Limit caffeine and address sleep hygiene\n7. If not converting, consider cardioversion after 48h of anticoagulation"}', now() - interval '1 day');

-- Patricia Davis (Cardiac, Stable Angina) - 7cca0171
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('7cca0171-7d60-4f3e-8e3a-d887d265b5eb', 'progress', 'signed', '{"subjective":"Patient is a 65-year-old female admitted for elective cardiac catheterization after positive stress test. Chest tightness with exertion x3 months, relieved by rest. No rest pain. Good exercise tolerance at baseline.","objective":"Vitals stable. ECG: normal sinus rhythm, no ST changes at rest. Troponin negative x2. Lipid panel: LDL 142, HDL 48. HbA1c 6.8%. Cath results: 70% stenosis of proximal LAD, 50% mid-RCA. Fractional flow reserve (FFR) LAD: 0.78.","assessment":"Stable angina with hemodynamically significant LAD stenosis (FFR <0.80). Suboptimally controlled cardiovascular risk factors.","plan":"1. Medical optimization: maximize statin, add ezetimibe\n2. PCI to LAD with DES — scheduled for tomorrow\n3. DAPT post-stent: ASA + Clopidogrel\n4. Diabetes management optimization\n5. Cardiac rehab referral post-intervention\n6. Lifestyle modifications counseling"}', now() - interval '6 hours');

-- =============================================
-- City Medical Center (Cerner) patients
-- =============================================

-- Thomas Jackson (Gen Med, DKA) - 214f478f
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('214f478f-30d4-4a2b-8373-448171b5bef9', 'progress', 'signed', '{"subjective":"PowerChart Entry — 28M presenting with polyuria, polydipsia, nausea, and abdominal pain x2 days. Known T1DM, non-compliant with insulin. Last ate yesterday.","objective":"Assessment: T 37.0, HR 118, BP 102/62, RR 28 (Kussmaul), SpO2 99%. BG 486 mg/dL. ABG: pH 7.18, pCO2 18, HCO3 8. Anion gap 28. BHB 6.2 mmol/L. K 5.8 (hemolyzed, repeat 5.2). BUN/Cr 32/1.4. UA: ketones 3+, glucose 4+.","assessment":"Diabetic ketoacidosis, severe (pH <7.2, HCO3 <10). Likely precipitated by insulin non-compliance. Need to rule out infection as precipitant.","plan":"1. DKA protocol: Insulin drip 0.14 units/kg/hr\n2. NS 1L bolus then 250 mL/hr\n3. K replacement per protocol (hold if K >5.3)\n4. BMP q2h, BG q1h\n5. Transition to SQ insulin when gap closes, eating, pH >7.3\n6. Endocrine consult for diabetes education\n7. Social work — assess barriers to medication compliance"}', now() - interval '1 day'),
('214f478f-30d4-4a2b-8373-448171b5bef9', 'progress', 'draft', '{"subjective":"Nausea resolved. Tolerating sips of clear liquids. No abdominal pain.","objective":"BG 198 mg/dL. ABG: pH 7.34, HCO3 18, AG 14 (closing). K 4.1. Cr 1.1 (improving). Insulin drip at 2 units/hr. Eating breakfast.","assessment":"DKA resolving — anion gap closing, pH normalizing. Ready for transition to subcutaneous insulin.","plan":"1. Transition to SQ insulin: Lantus 20 units at bedtime + Humalog sliding scale\n2. Overlap drip x2h after first Lantus dose\n3. Diabetes education by certified educator\n4. Ensure PCP follow-up within 1 week\n5. Continuous glucose monitor discussion\n6. Target discharge tomorrow if stable on SQ regimen"}', now());

-- Charles Harris (Gen Med, GI bleed) - 7664d476
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('7664d476-a190-4b7c-9501-f215852b0ac0', 'progress', 'signed', '{"subjective":"PowerChart Entry — 71M with 2 episodes of melena and lightheadedness. On aspirin 81mg and warfarin for mechanical aortic valve. Last INR 3.8 (supratherapeutic).","objective":"HR 104, BP 98/58 (orthostatic positive), Hgb 7.2 (baseline 12.5), INR 3.8, BUN 45, Cr 1.1. NG lavage: coffee-ground material. Type & screen sent. 2 units pRBC ordered.","assessment":"Acute upper GI hemorrhage with hemodynamic compromise. Supratherapeutic anticoagulation as contributing factor. Mechanical valve complicates anticoagulation reversal.","plan":"1. IV PPI: Pantoprazole 80mg bolus then 8mg/hr drip\n2. Transfuse 2 units pRBC\n3. Hold warfarin — do NOT give vitamin K (mechanical valve)\n4. GI consult for urgent EGD\n5. Cardiology consult re: anticoagulation management\n6. Keep 2 units crossmatched\n7. Serial H/H q6h"}', now() - interval '8 hours');

-- Joseph Garcia (Gen Med, Cellulitis) - acd69f21
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('acd69f21-b097-4f37-8af1-1f16e8f7e3f1', 'progress', 'signed', '{"subjective":"PowerChart Entry — 55M with progressively worsening right lower leg redness, swelling, and pain x4 days. Failed outpatient oral antibiotics (cephalexin x3 days). History of recurrent cellulitis in same leg. Diabetes (HbA1c 9.2).","objective":"T 38.4°C, HR 88, BP 140/82. R lower leg: erythema extending from ankle to mid-calf, marked with skin marker. Warm, tender, no crepitus. No fluctuance. DP pulse palpable. WBC 14.2. BG 268.","assessment":"Non-purulent cellulitis of right lower extremity, failing oral therapy. Poorly controlled diabetes as risk factor.","plan":"1. IV Vancomycin 1g q12h + Piperacillin-tazobactam 3.375g q8h\n2. Mark erythema borders and reassess q12h\n3. Elevate extremity\n4. Glycemic management: insulin sliding scale\n5. Wound care nursing consult\n6. If no improvement 48h, consider CT to rule out abscess\n7. Endocrine consult for diabetes optimization"}', now() - interval '1 day');

-- Susan White (Oncology, Neutropenic fever) - dde71bdf
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('dde71bdf-0c6c-4e4c-b1fe-12f39e4d524d', 'progress', 'signed', '{"subjective":"PowerChart Entry — 58F with AML, currently on induction chemotherapy (7+3 regimen, day 14). Developed fever to 38.9°C with rigors 2 hours ago. Mild sore throat. Port site non-tender.","objective":"T 38.9°C, HR 108, BP 110/68, RR 20, SpO2 97%. ANC 120 (severely neutropenic). WBC 0.4. Hgb 7.8. Plt 22K. CXR: no infiltrate. Blood cultures x2 (peripheral + port) drawn. UA: bland. Lactate 1.4.","assessment":"Febrile neutropenia in setting of AML induction chemotherapy. High risk by MASCC score. No obvious source identified.","plan":"1. Empiric: Cefepime 2g IV q8h (start within 1 hour)\n2. If still febrile at 72h, add vancomycin and antifungal coverage\n3. Daily CBC with differential\n4. Transfuse pRBC if Hgb <7, platelets if <10K or bleeding\n5. Neutropenic precautions\n6. Oncology aware — continue to monitor for count recovery\n7. G-CSF per oncology protocol"}', now() - interval '6 hours'),
('dde71bdf-0c6c-4e4c-b1fe-12f39e4d524d', 'progress', 'draft', '{"subjective":"Fever broke overnight. No new symptoms. Tolerating PO.","objective":"Tmax 37.8°C (improved). ANC still 80. Blood cultures: no growth at 24h. Port site clean. No mucositis.","assessment":"Febrile neutropenia responding to empiric cefepime. Await culture results and count recovery.","plan":"1. Continue cefepime\n2. Monitor cultures at 48h checkpoint\n3. If afebrile 48h and cultures negative, may narrow\n4. Continue transfusion support per thresholds\n5. Anticipate count recovery days 21-28"}', now());

-- Elizabeth Robinson (Oncology, Chemo toxicity) - 76c155d8
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('76c155d8-ba5e-45c6-98c1-dcd2ef99b790', 'progress', 'signed', '{"subjective":"PowerChart Entry — 62F with stage IIIB NSCLC on carboplatin/pemetrexed cycle 4. Presenting with severe nausea, vomiting x3 days, unable to keep down PO medications. Reports fatigue and decreased urine output.","objective":"BP 94/60, HR 102, T 37.1°C. Mucous membranes dry. Skin tenting present. BMP: Na 128, K 3.1, Cr 1.8 (baseline 0.8), BUN 42. Mg 1.4. CBC: WBC 2.8, ANC 1200, Hgb 9.1, Plt 118K.","assessment":"Chemotherapy-induced nausea/vomiting with dehydration and acute kidney injury (KDIGO stage 2). Electrolyte derangements. Borderline neutropenia.","plan":"1. Aggressive IV hydration: NS 200mL/hr x4 hours then 125mL/hr\n2. Electrolyte repletion: KCl 40mEq IV, MgSO4 2g IV\n3. Antiemetics: Ondansetron 4mg IV q6h + Dexamethasone 8mg IV daily\n4. Hold chemotherapy until resolved\n5. Recheck BMP in 6 hours\n6. Oncology: discuss dose reduction for next cycle\n7. Nutrition consult for oral supplementation"}', now() - interval '1 day');

-- Margaret Martin (Oncology, Stable) - cac05b94
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('cac05b94-1d46-42be-a523-4d4ffbdb128a', 'progress', 'signed', '{"subjective":"PowerChart Entry — 70F with breast cancer (ER+/PR+/HER2-), admitted for management of malignant pleural effusion. Progressive dyspnea on exertion over 2 weeks. Mild dry cough. No fever.","objective":"RR 22, SpO2 93% on RA, BP 128/76. Decreased breath sounds right base. CXR: large right pleural effusion. Cytology pending from thoracentesis (1.2L serosanguinous fluid removed). Post-procedure CXR: re-expansion, no pneumothorax.","assessment":"Malignant pleural effusion secondary to metastatic breast cancer. Symptomatic improvement after therapeutic thoracentesis.","plan":"1. Post-thoracentesis monitoring\n2. Cytology and cell block results pending\n3. Pulmonology consult for pleurodesis vs indwelling catheter\n4. Continue current systemic therapy\n5. Pain management\n6. Palliative care consult for goals of care discussion"}', now() - interval '2 days');

-- =============================================
-- Regional Health System (Meditech) patients
-- =============================================

-- Michael Clark (ED, Trauma) - b91b0d95
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('b91b0d95-cabd-434b-9321-1ff47ab67f49', 'progress', 'signed', '{"subjective":"MEDITECH ED NOTE — 42M MVC, restrained driver, T-bone collision at intersection. +LOC at scene, GCS 14 on arrival (E4V4M6). C-collar in place. Complains of chest and left leg pain.","objective":"Primary survey: Airway patent, RR 24, SpO2 94% on 15L NRB, HR 112, BP 100/68. FAST: + free fluid in Morrison pouch. CXR: left-sided rib fractures (ribs 4-7), small left pneumothorax. Left femur: shortened and externally rotated. CT head: no acute intracranial hemorrhage. CT C-spine: no fracture.","assessment":"Polytrauma: 1) Left hemopneumothorax with rib fractures 2) Suspected left femoral shaft fracture 3) Possible intra-abdominal injury (positive FAST) 4) Mild TBI (GCS 14, +LOC).","plan":"1. Left chest tube placement (28Fr)\n2. Massive transfusion protocol standby\n3. 2 units pRBC now\n4. CT abdomen/pelvis with contrast\n5. Orthopedic consult for femur\n6. Neuro checks q1h\n7. Trauma surgery evaluation\n8. Type & crossmatch 4 additional units"}', now() - interval '3 hours'),
('b91b0d95-cabd-434b-9321-1ff47ab67f49', 'procedure', 'signed', '{"subjective":"Procedure: Left chest tube insertion","objective":"Indication: Left hemopneumothorax. Procedure: Left chest tube (28Fr) inserted at 5th ICS, anterior axillary line under sterile technique. Immediate output: 400mL serosanguinous fluid. Good lung re-expansion on post-procedure CXR. Tube secured and to water seal.","assessment":"Successful chest tube placement with good drainage and lung re-expansion.","plan":"1. Monitor chest tube output q1h\n2. If >200mL/hr for 2 consecutive hours, contact trauma surgery\n3. Post-procedure CXR in 6h\n4. Pain management for rib fractures"}', now() - interval '2 hours');

-- Jessica King (ED, Asthma exacerbation) - 288ba172
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('288ba172-299b-453e-8465-8f88e12873f8', 'progress', 'signed', '{"subjective":"MEDITECH ED NOTE — 33F with known severe persistent asthma presenting with acute exacerbation. URI symptoms x3 days, progressive wheezing and dyspnea. Used rescue inhaler 8 times today without relief. Last ER visit 3 months ago for similar.","objective":"RR 32, HR 118, SpO2 89% on RA → 93% on 4L NC. Unable to speak in full sentences. Diffuse expiratory wheezing bilaterally with decreased air movement. Peak flow 120 L/min (personal best 380). ABG: pH 7.42, pCO2 36 (normalizing — concerning for tiring).","assessment":"Severe acute asthma exacerbation with poor air movement and near-normal pCO2 (impending respiratory failure if worsening). Multiple ER visits suggesting inadequately controlled asthma.","plan":"1. Continuous nebulized albuterol + ipratropium\n2. Methylprednisolone 125mg IV now\n3. Magnesium sulfate 2g IV over 20 min\n4. Repeat peak flow in 1 hour\n5. If not improving: BiPAP trial\n6. If pCO2 rises or clinical decline: prepare for intubation\n7. Admit to step-down unit\n8. Allergy/pulmonology referral for controller optimization"}', now() - interval '4 hours');

-- Linda Lewis (Surgical, Post-op colectomy) - 90cbf7e5
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('90cbf7e5-5a35-4221-8e57-d932017ab4bf', 'progress', 'signed', '{"subjective":"MEDITECH SURGICAL NOTE — POD 2 from laparoscopic right hemicolectomy for cecal mass. Patient reports mild incisional pain (3/10). No nausea. Has passed flatus. No bowel movement yet.","objective":"T 37.4°C, HR 76, BP 128/78. Abdomen: soft, mildly tender at port sites, no distension. Incisions clean and dry. Bowel sounds present in all quadrants. JP drain: minimal serous output. Diet: tolerating clear liquids.","assessment":"Post-op day 2 from laparoscopic right hemicolectomy. Return of bowel function (flatus). Recovering well. Pathology pending.","plan":"1. Advance diet to regular as tolerated\n2. Increase ambulation — goal 4 laps/day\n3. Continue PCA → transition to PO pain meds today\n4. Remove JP drain if output continues low\n5. Path results expected tomorrow\n6. DVT prophylaxis until ambulatory\n7. Target discharge POD 3-4"}', now() - interval '6 hours');

-- Christopher Young (Surgical, Appendicitis) - 6cfb3b21
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('6cfb3b21-9afb-449c-8e03-c00100fca84f', 'progress', 'signed', '{"subjective":"MEDITECH SURGICAL NOTE — 38M POD 0 from laparoscopic appendectomy for perforated appendicitis. Surgery uncomplicated. Currently NPO. Reports surgical site pain 4/10.","objective":"T 38.1°C, HR 84, BP 124/76, RR 16. Abdomen: mild distension, tender at umbilical port site. No peritoneal signs. WBC 16.4 (pre-op 22.1). Drain in RLQ: 50mL seropurulent output.","assessment":"Status post laparoscopic appendectomy for perforated appendicitis. Low-grade fever expected POD 0. WBC trending down.","plan":"1. Continue IV antibiotics: Ceftriaxone + Metronidazole x5 days\n2. Advance diet when passing flatus\n3. Monitor drain output and character\n4. If fever >38.5°C after POD 2, CT to rule out abscess\n5. Early ambulation\n6. Anticipate discharge POD 2-3 with PO antibiotics"}', now() - interval '12 hours');

-- Matthew Adams (Surgical, Bowel obstruction) - 029266f0
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('029266f0-acc4-45df-96b3-a47bc96fdf6e', 'progress', 'signed', '{"subjective":"MEDITECH SURGICAL NOTE — 67M with history of prior abdominal surgeries presenting with 2 days of crampy abdominal pain, nausea, vomiting, and obstipation. Last BM 3 days ago.","objective":"T 37.6°C, HR 98, BP 136/84. Abdomen: distended, diffusely tender without peritoneal signs. High-pitched tinkling bowel sounds. CT abdomen: small bowel obstruction with transition point in right lower quadrant, likely adhesive. No pneumatosis or free air. Lactate 1.2.","assessment":"Adhesive small bowel obstruction, partial. No signs of strangulation or ischemia currently.","plan":"1. NGT decompression — 800mL bilious output on placement\n2. NPO, IV fluids NS at 125mL/hr\n3. Serial abdominal exams q4h\n4. Gastrografin challenge tomorrow if no improvement\n5. If peritoneal signs or clinical decline → OR for lysis of adhesions\n6. DVT prophylaxis\n7. Nutrition consult if NPO >5 days"}', now() - interval '1 day'),
('029266f0-acc4-45df-96b3-a47bc96fdf6e', 'progress', 'draft', '{"subjective":"Mild improvement in pain. NGT output decreasing. No vomiting since NGT placed.","objective":"NGT output: 300mL/8h shift (↓). Abdomen less distended. Mild tenderness. No peritoneal signs. KUB: still dilated loops but improved air-fluid levels. Lactate 0.9.","assessment":"SBO with early signs of resolution. Conservative management appropriate. No surgical indicators at this time.","plan":"1. Gastrografin 100mL via NGT today\n2. Follow-up KUB in 6 hours\n3. If contrast reaches colon, clamp NGT and trial clear liquids\n4. Continue serial abdominal exams\n5. If no resolution by day 3, surgical intervention"}', now());

-- David Walker (Rehab) - 88ff7bd5
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('88ff7bd5-e64b-4603-98ec-5b2d4fd32136', 'progress', 'signed', '{"subjective":"MEDITECH REHAB NOTE — 55M, day 5 of inpatient rehabilitation following right hemispheric CVA. Left hemiparesis improving. Able to stand with moderate assist. Speech therapy working on mild neglect.","objective":"BP 138/82, HR 72. Neuro: Left UE 3/5 strength (↑ from 2/5 admission), Left LE 3+/5. FIM score: 62 (admission 45). Ambulating 50 feet with rolling walker and min assist. Tolerating regular diet with modified consistency liquids.","assessment":"Improving post-CVA. Making functional gains in PT/OT. Swallow function stable. Target FIM >80 for home discharge.","plan":"1. Continue PT/OT/ST 3 hours daily\n2. Continue secondary stroke prevention: ASA, statin, lisinopril\n3. INR monitoring for warfarin (if afib)\n4. Family training for home modifications\n5. Neuropsychology evaluation for cognitive rehab\n6. Estimated discharge in 7-10 days to home with home health"}', now() - interval '2 days');

-- Daniel Wright (Rehab) - 184b277c
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('184b277c-2e03-4b7f-9741-2bc27694fea8', 'progress', 'signed', '{"subjective":"MEDITECH REHAB NOTE — 48M, week 2 of inpatient rehabilitation following T12 burst fracture with spinal cord injury (ASIA C). Progressing with transfers. Frustrated with pace of recovery.","objective":"Vitals stable. Neuro: bilateral LE 2-3/5 strength, sensation intact to light touch below T12, proprioception impaired. Bladder: intermittent catheterization q6h, residuals 100-150mL. Skin: intact, no pressure injuries. FIM: 58.","assessment":"Incomplete spinal cord injury (ASIA C) with motor incomplete paraparesis. Making gradual functional gains. Neuropathic pain and emotional adjustment challenges.","plan":"1. Intensive PT/OT: transfers, wheelchair mobility, standing frame\n2. Gabapentin 300mg TID for neuropathic pain\n3. Bladder training program — timed voiding trials\n4. Psychology consult for adjustment counseling\n5. Pressure injury prevention protocol\n6. Family meeting re: home modifications and equipment\n7. Projected discharge in 3-4 weeks"}', now() - interval '3 days');

-- Nancy Hall (Long-term Care) - a1ba7991
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('a1ba7991-4565-47a9-a884-705e81de436f', 'progress', 'signed', '{"subjective":"MEDITECH LTC NOTE — 82F with advanced dementia (GDS 6), CHF, and CKD stage 3b. Caregiver reports patient more confused than baseline over past 2 days. Decreased oral intake. No fever, cough, or urinary symptoms.","objective":"T 37.0°C, HR 78, BP 108/62, SpO2 95% on RA. Weight 52kg (↓1kg from last month). Alert but disoriented to time and place. No focal neuro deficits beyond baseline. UA: trace leukocytes, negative nitrite. BMP: Na 132, K 4.2, Cr 1.6 (baseline 1.4), BUN 38.","assessment":"Acute-on-chronic cognitive decline. Differential: dehydration, UTI, medication effect, disease progression. Mild AKI likely pre-renal.","plan":"1. PO fluid challenge: 500mL over 4 hours\n2. Repeat BMP tomorrow\n3. Monitor I/O closely\n4. Medication review — hold metformin (Cr elevated)\n5. If worsening confusion, urine culture and CXR\n6. Palliative care team aware — comfort-focused care plan\n7. Family updated on status"}', now() - interval '1 day');

-- Karen Scott (Long-term Care) - 9ba6d176
INSERT INTO public.clinical_notes (patient_id, note_type, status, content, created_at) VALUES
('9ba6d176-f93a-4fd6-b28a-230bcf252eab', 'progress', 'signed', '{"subjective":"MEDITECH LTC NOTE — 78F with Parkinson disease, on chronic L-dopa. Staff reports increased falls x2 this week (no injuries). Episodes of freezing gait more frequent. Sleep disturbance with vivid dreams.","objective":"BP 142/78 sitting → 108/62 standing (orthostatic +). HR 68. Neuro: resting tremor bilateral (R>L), cogwheel rigidity, shuffling gait with festination. MMSE 24/30. No injuries from falls.","assessment":"Parkinson disease with motor fluctuations and orthostatic hypotension contributing to falls. Possible medication timing issues. REM sleep behavior disorder.","plan":"1. Neurology consult for medication adjustment\n2. Fall prevention protocol: bed alarm, non-slip footwear\n3. PT for gait training and balance\n4. Consider fludrocortisone for orthostatic hypotension\n5. Adjust L-dopa timing (consider extended release)\n6. Melatonin trial for REM sleep behavior disorder\n7. Weekly fall risk reassessment"}', now() - interval '4 days');

-- =============================================
-- SEED PATIENT VITALS (insights + trends)
-- =============================================

-- Memorial General (Epic)
INSERT INTO public.patient_vitals (patient_id, insights, trends) VALUES
-- Robert Chen (ICU, Sepsis)
('2887cfc2-9a39-49e2-b838-01c1e0463b51',
'[{"id":"ins-rc-1","title":"Vasopressor Wean Success","description":"Successfully weaned off norepinephrine at 0400. MAP maintained >65 without support for 8 hours. Lactate normalized at 1.8.","timestamp":"Today, 06:15","severity":"success","sources":["Vitals Trend","ICU Flowsheet","ABG Results"]},{"id":"ins-rc-2","title":"Blood Culture Alert","description":"Gram-negative rods identified in 2/2 blood culture bottles. Speciation and sensitivities pending. Current empiric coverage with meropenem is appropriate.","timestamp":"Today, 05:30","severity":"warning","sources":["Microbiology","Pharmacy Records"]},{"id":"ins-rc-3","title":"ERCP Scheduled","description":"GI has confirmed ERCP for tomorrow AM. NPO after midnight. Anesthesia pre-op evaluation complete.","timestamp":"Today, 14:00","severity":"info","sources":["GI Consult Note","OR Schedule"]}]',
'[{"id":"tr-rc-1","label":"MAP","value":"72 mmHg","direction":"up","change":"↑ Off pressors"},{"id":"tr-rc-2","label":"Lactate","value":"1.8 mmol/L","direction":"down","change":"↓ from 4.1"},{"id":"tr-rc-3","label":"WBC","value":"14.1 K","direction":"down","change":"↓ from 18.2"},{"id":"tr-rc-4","label":"Temperature","value":"38.4°C","direction":"down","change":"↓ trending"}]'),

-- Maria Santos (ICU, STEMI)
('77f4db2e-9d3b-47aa-8d56-71e84129b300',
'[{"id":"ins-ms-1","title":"Troponin Down-trending","description":"Serial troponins: 12.4 → 8.2 → 4.1. Expected post-PCI decline. No evidence of re-occlusion.","timestamp":"Today, 08:00","severity":"success","sources":["Lab Results","Cardiology Notes"]},{"id":"ins-ms-2","title":"Initiate ACE Inhibitor","description":"Patient hemodynamically stable. EF 35% — guideline-directed medical therapy requires ACE inhibitor. Recommend starting Lisinopril 2.5mg today.","timestamp":"Today, 07:30","severity":"warning","sources":["Echo Report","ACC/AHA Guidelines","Vitals Trend"]}]',
'[{"id":"tr-ms-1","label":"Troponin I","value":"4.1 ng/mL","direction":"down","change":"↓ 67%"},{"id":"tr-ms-2","label":"Heart Rate","value":"72 bpm","direction":"stable"},{"id":"tr-ms-3","label":"EF","value":"35%","direction":"stable"},{"id":"tr-ms-4","label":"BP","value":"118/72","direction":"stable"}]'),

-- Richard Moore (ICU, Resp Failure)
('c899d27a-4069-4f15-bcc6-ff1c4a55cb5f',
'[{"id":"ins-rm-1","title":"P/F Ratio Improving","description":"P/F ratio improved from 130 to 230. ARDS resolving. Ready for spontaneous breathing trial.","timestamp":"Today, 06:00","severity":"success","sources":["ABG Results","Vent Settings","Respiratory Therapy"]},{"id":"ins-rm-2","title":"Culture-Directed Therapy","description":"Sputum culture: S. pneumoniae (penicillin-sensitive). Recommend narrowing from pip/tazo to ampicillin-sulbactam.","timestamp":"Today, 07:15","severity":"info","sources":["Microbiology","Antimicrobial Stewardship"]}]',
'[{"id":"tr-rm-1","label":"P/F Ratio","value":"230","direction":"up","change":"↑ from 130"},{"id":"tr-rm-2","label":"FiO2","value":"40%","direction":"down","change":"↓ from 60%"},{"id":"tr-rm-3","label":"PEEP","value":"8 cmH2O","direction":"down","change":"↓ from 10"},{"id":"tr-rm-4","label":"WBC","value":"15.3 K","direction":"down","change":"↓ from 22.1"}]'),

-- William Thompson (Med-Surg, CHF)
('7ddc5fc4-597d-42ce-b0db-53ff7391eab8',
'[{"id":"ins-wt-1","title":"Excellent Diuretic Response","description":"Net negative 2.1L in 24 hours. Weight down 3kg. Patient reports significant symptom improvement — sleeping flat for first time in weeks.","timestamp":"Today, 07:00","severity":"success","sources":["I/O Records","Nursing Assessment","Daily Weight"]},{"id":"ins-wt-2","title":"Medication Access Concern","description":"Social work identified patient ran out of furosemide due to cost. Pharmacy assistance program application in progress.","timestamp":"Yesterday, 14:00","severity":"warning","sources":["Social Work Note","Pharmacy Consult"]}]',
'[{"id":"tr-wt-1","label":"Weight","value":"95 kg","direction":"down","change":"↓ 3kg"},{"id":"tr-wt-2","label":"BNP","value":"1240 pg/mL","direction":"down","change":"↓ from 1842"},{"id":"tr-wt-3","label":"Creatinine","value":"1.4","direction":"down","change":"↓ from 1.6"},{"id":"tr-wt-4","label":"Net I/O","value":"-2.1L","direction":"down"}]'),

-- Dorothy Williams (Med-Surg, Pneumonia)
('2af62d29-02ee-44f5-b708-f4c8290de779',
'[{"id":"ins-dw-1","title":"Responding to Antibiotics","description":"Temperature trending down, WBC improving. Confusion clearing. On track for PO antibiotic transition.","timestamp":"Today, 08:00","severity":"info","sources":["Vitals Trend","Lab Results","Nursing Assessment"]}]',
'[{"id":"tr-dw-1","label":"Temperature","value":"37.8°C","direction":"down","change":"↓ from 38.6"},{"id":"tr-dw-2","label":"SpO2","value":"95%","direction":"up","change":"↑ from 93%"},{"id":"tr-dw-3","label":"WBC","value":"11.2 K","direction":"down","change":"↓ from 13.8"},{"id":"tr-dw-4","label":"Mental Status","value":"Alert/Oriented","direction":"up"}]'),

-- Barbara Taylor (Med-Surg, Post-op hip)
('374cb9a1-0e4b-4655-b867-ac14e996f3cd',
'[{"id":"ins-bt-1","title":"Meeting PT Milestones","description":"Ambulated 150 feet with rolling walker. Drain output below threshold for removal. On track for discharge to rehab tomorrow.","timestamp":"Today, 10:00","severity":"success","sources":["PT Evaluation","Surgical Drain Log"]},{"id":"ins-bt-2","title":"Drain Ready for Removal","description":"JP drain output 25mL last shift — below 30mL threshold. Recommend removal today.","timestamp":"Today, 06:00","severity":"info","sources":["Nursing Flowsheet"]}]',
'[{"id":"tr-bt-1","label":"Pain Score","value":"3/10","direction":"down","change":"↓ from 5/10"},{"id":"tr-bt-2","label":"Drain Output","value":"25 mL","direction":"down","change":"↓ from 120"},{"id":"tr-bt-3","label":"Hemoglobin","value":"9.4","direction":"stable"},{"id":"tr-bt-4","label":"Ambulation","value":"150 ft","direction":"up"}]'),

-- James Anderson (Cardiac, Afib)
('4f8084f1-18bb-4bb4-8804-bde640f7c574',
'[{"id":"ins-ja-1","title":"Rate Control Needed","description":"Heart rate remains >130 despite initial diltiazem bolus. Drip running at 10mg/hr. May need dose uptitration or additional agent.","timestamp":"Today, 09:00","severity":"warning","sources":["Telemetry","MAR","Cardiology Consult"]},{"id":"ins-ja-2","title":"Anticoagulation Initiated","description":"CHA₂DS₂-VASc score 3 — anticoagulation indicated. Apixaban 5mg BID started. No contraindications identified.","timestamp":"Today, 08:00","severity":"info","sources":["Clinical Assessment","Pharmacy Review"]}]',
'[{"id":"tr-ja-1","label":"Heart Rate","value":"132 bpm","direction":"down","change":"↓ from 142"},{"id":"tr-ja-2","label":"Rhythm","value":"Afib/RVR","direction":"stable"},{"id":"tr-ja-3","label":"Potassium","value":"4.2","direction":"up","change":"↑ repleted"},{"id":"tr-ja-4","label":"Magnesium","value":"2.1","direction":"up","change":"↑ repleted"}]'),

-- Patricia Davis (Cardiac, Stable Angina)
('7cca0171-7d60-4f3e-8e3a-d887d265b5eb',
'[{"id":"ins-pd-1","title":"PCI Scheduled Tomorrow","description":"Cardiology confirmed PCI with DES to LAD for tomorrow AM. FFR 0.78 confirms hemodynamic significance. Pre-procedure checklist complete.","timestamp":"Today, 15:00","severity":"info","sources":["Cath Lab Report","Cardiology Note","OR Schedule"]}]',
'[{"id":"tr-pd-1","label":"FFR (LAD)","value":"0.78","direction":"stable"},{"id":"tr-pd-2","label":"LDL","value":"142 mg/dL","direction":"stable"},{"id":"tr-pd-3","label":"HbA1c","value":"6.8%","direction":"stable"},{"id":"tr-pd-4","label":"Troponin","value":"Negative","direction":"stable"}]'),

-- City Medical Center (Cerner)
-- Thomas Jackson (Gen Med, DKA)
('214f478f-30d4-4a2b-8373-448171b5bef9',
'[{"id":"ins-tj-1","title":"Anion Gap Closing","description":"AG narrowing from 28 to 14. pH improving from 7.18 to 7.34. Ready for transition to subcutaneous insulin.","timestamp":"Today, 07:00","severity":"success","sources":["BMP Trend","ABG Results","Insulin Drip Protocol"]},{"id":"ins-tj-2","title":"Compliance Barriers Identified","description":"Social work assessment: patient lost insurance 2 months ago, unable to afford insulin. Assistance program referral initiated.","timestamp":"Today, 09:00","severity":"warning","sources":["Social Work Note","Pharmacy Benefits"]}]',
'[{"id":"tr-tj-1","label":"Blood Glucose","value":"198 mg/dL","direction":"down","change":"↓ from 486"},{"id":"tr-tj-2","label":"pH","value":"7.34","direction":"up","change":"↑ from 7.18"},{"id":"tr-tj-3","label":"Anion Gap","value":"14","direction":"down","change":"↓ from 28"},{"id":"tr-tj-4","label":"Potassium","value":"4.1","direction":"down","change":"↓ normalized"}]'),

-- Charles Harris (Gen Med, GI Bleed)
('7664d476-a190-4b7c-9501-f215852b0ac0',
'[{"id":"ins-ch-1","title":"Active Upper GI Hemorrhage","description":"Hemoglobin dropped from 12.5 to 7.2. Positive NG aspirate. Supratherapeutic INR 3.8 contributing to bleeding. Mechanical valve complicates anticoagulation reversal.","timestamp":"Today, 06:00","severity":"critical","sources":["Lab Results","NG Aspirate","Coagulation Panel"]},{"id":"ins-ch-2","title":"Urgent EGD Required","description":"GI consult obtained. EGD scheduled for this morning. Patient NPO and IV PPI running. Blood products available.","timestamp":"Today, 07:30","severity":"warning","sources":["GI Consult","Blood Bank","Pharmacy"]}]',
'[{"id":"tr-ch-1","label":"Hemoglobin","value":"8.4 g/dL","direction":"up","change":"↑ post-transfusion"},{"id":"tr-ch-2","label":"INR","value":"3.8","direction":"up","change":"↑ supratherapeutic"},{"id":"tr-ch-3","label":"Heart Rate","value":"96 bpm","direction":"down","change":"↓ post-resuscitation"},{"id":"tr-ch-4","label":"BP","value":"112/68","direction":"up","change":"↑ improving"}]'),

-- Joseph Garcia (Gen Med, Cellulitis)
('acd69f21-b097-4f37-8af1-1f16e8f7e3f1',
'[{"id":"ins-jg-1","title":"Failed Outpatient Therapy","description":"Cellulitis progressed despite 3 days of oral cephalexin. Erythema extending. IV antibiotics initiated. Monitoring for improvement at 48h mark.","timestamp":"Yesterday, 16:00","severity":"warning","sources":["Admission Note","Wound Assessment","Pharmacy Records"]},{"id":"ins-jg-2","title":"Glycemic Control Poor","description":"HbA1c 9.2%, random BG 268. Poor glycemic control is a major risk factor for recurrent cellulitis. Endocrine consult placed.","timestamp":"Today, 08:00","severity":"warning","sources":["Lab Results","Endocrine Consult"]}]',
'[{"id":"tr-jg-1","label":"Temperature","value":"37.6°C","direction":"down","change":"↓ from 38.4"},{"id":"tr-jg-2","label":"WBC","value":"12.8 K","direction":"down","change":"↓ from 14.2"},{"id":"tr-jg-3","label":"Erythema","value":"Stable","direction":"stable","change":"No spread"},{"id":"tr-jg-4","label":"Blood Glucose","value":"198 mg/dL","direction":"down","change":"↓ on insulin SS"}]'),

-- Susan White (Oncology, Neutropenic Fever)
('dde71bdf-0c6c-4e4c-b1fe-12f39e4d524d',
'[{"id":"ins-sw-1","title":"Febrile Neutropenia — High Risk","description":"ANC 120 with fever 38.9°C on day 14 of AML induction. Empiric cefepime started within 45 minutes. Blood cultures pending at 24h.","timestamp":"Today, 06:00","severity":"critical","sources":["CBC","Blood Cultures","Oncology Protocol"]},{"id":"ins-sw-2","title":"Transfusion Thresholds","description":"Hgb 7.8, Plt 22K. Approaching transfusion thresholds. Monitor for bleeding signs.","timestamp":"Today, 07:00","severity":"warning","sources":["CBC","Transfusion Medicine"]}]',
'[{"id":"tr-sw-1","label":"ANC","value":"80","direction":"down","change":"↓ from 120"},{"id":"tr-sw-2","label":"Temperature","value":"37.8°C","direction":"down","change":"↓ from 38.9"},{"id":"tr-sw-3","label":"Platelets","value":"22K","direction":"stable"},{"id":"tr-sw-4","label":"Hemoglobin","value":"7.8","direction":"stable"}]'),

-- Elizabeth Robinson (Oncology, Chemo toxicity)
('76c155d8-ba5e-45c6-98c1-dcd2ef99b790',
'[{"id":"ins-er-1","title":"Acute Kidney Injury from Dehydration","description":"Creatinine rose from 0.8 to 1.8 (KDIGO Stage 2) due to chemotherapy-induced vomiting and dehydration. Aggressive IV hydration initiated.","timestamp":"Yesterday, 18:00","severity":"critical","sources":["BMP Trend","Oncology Note","I/O Records"]},{"id":"ins-er-2","title":"Chemotherapy Held","description":"Carboplatin/pemetrexed held until AKI resolves and electrolytes normalize. Oncology discussing dose reduction for next cycle.","timestamp":"Today, 08:00","severity":"warning","sources":["Oncology Note","Pharmacy"]}]',
'[{"id":"tr-er-1","label":"Creatinine","value":"1.5","direction":"down","change":"↓ from 1.8"},{"id":"tr-er-2","label":"Sodium","value":"131","direction":"up","change":"↑ from 128"},{"id":"tr-er-3","label":"Potassium","value":"3.8","direction":"up","change":"↑ repleted"},{"id":"tr-er-4","label":"UOP","value":"1.2 mL/kg/hr","direction":"up","change":"↑ responding"}]'),

-- Margaret Martin (Oncology, Stable)
('cac05b94-1d46-42be-a523-4d4ffbdb128a',
'[{"id":"ins-mm-1","title":"Post-Thoracentesis Stable","description":"1.2L drained successfully. CXR confirms lung re-expansion, no pneumothorax. SpO2 improved to 96% on room air.","timestamp":"Today, 10:00","severity":"success","sources":["Procedure Note","CXR","Vitals"]},{"id":"ins-mm-2","title":"Cytology Pending","description":"Pleural fluid sent for cytology and cell block. Results expected in 2-3 days. Will guide further management.","timestamp":"Today, 10:30","severity":"info","sources":["Pathology","Procedure Note"]}]',
'[{"id":"tr-mm-1","label":"SpO2","value":"96%","direction":"up","change":"↑ from 93%"},{"id":"tr-mm-2","label":"RR","value":"18/min","direction":"down","change":"↓ from 22"},{"id":"tr-mm-3","label":"Pleural Fluid","value":"1.2L drained","direction":"stable"},{"id":"tr-mm-4","label":"Pain","value":"2/10","direction":"down","change":"↓ from 4/10"}]'),

-- Regional Health System (Meditech)
-- Michael Clark (ED, Trauma)
('b91b0d95-cabd-434b-9321-1ff47ab67f49',
'[{"id":"ins-mc-1","title":"Positive FAST — Possible Intra-abdominal Injury","description":"Free fluid in Morrison pouch on bedside FAST exam. CT abdomen/pelvis ordered. Massive transfusion protocol on standby.","timestamp":"Today, arrival","severity":"critical","sources":["FAST Exam","Trauma Assessment","CT Pending"]},{"id":"ins-mc-2","title":"Left Hemopneumothorax — Chest Tube Placed","description":"28Fr chest tube with 400mL initial output. Good lung re-expansion on post-procedure film. Monitoring for ongoing hemorrhage.","timestamp":"Today, +30min","severity":"warning","sources":["Procedure Note","CXR","Chest Tube Output"]}]',
'[{"id":"tr-mc-1","label":"BP","value":"108/72","direction":"up","change":"↑ post-resuscitation"},{"id":"tr-mc-2","label":"Heart Rate","value":"98 bpm","direction":"down","change":"↓ from 112"},{"id":"tr-mc-3","label":"GCS","value":"14","direction":"stable"},{"id":"tr-mc-4","label":"Chest Tube","value":"400mL initial","direction":"stable"}]'),

-- Jessica King (ED, Asthma)
('288ba172-299b-453e-8465-8f88e12873f8',
'[{"id":"ins-jk-1","title":"Impending Respiratory Failure","description":"Near-normal pCO2 (36) with severe obstruction is concerning for respiratory muscle fatigue. If pCO2 rises, intubation may be needed. BiPAP trial recommended.","timestamp":"Today, 08:00","severity":"critical","sources":["ABG","Peak Flow","Respiratory Assessment"]},{"id":"ins-jk-2","title":"Frequent ED Visits","description":"3rd ED visit in 6 months for asthma exacerbation. Current controller regimen inadequate. Allergy/pulmonology referral needed for optimization.","timestamp":"Today, 08:30","severity":"warning","sources":["ED Visit History","Medication List"]}]',
'[{"id":"tr-jk-1","label":"Peak Flow","value":"120 L/min","direction":"down","change":"32% of best"},{"id":"tr-jk-2","label":"SpO2","value":"93%","direction":"up","change":"↑ on 4L"},{"id":"tr-jk-3","label":"pCO2","value":"36 mmHg","direction":"stable","change":"Concerning"},{"id":"tr-jk-4","label":"RR","value":"28/min","direction":"down","change":"↓ from 32"}]'),

-- Linda Lewis (Surgical, Post-op)
('90cbf7e5-5a35-4221-8e57-d932017ab4bf',
'[{"id":"ins-ll-1","title":"Return of Bowel Function","description":"Patient has passed flatus and tolerating clear liquids. Bowel sounds present. Ready to advance diet.","timestamp":"Today, 08:00","severity":"success","sources":["Nursing Assessment","Surgical Rounds"]},{"id":"ins-ll-2","title":"Pathology Pending","description":"Cecal mass pathology results expected tomorrow. Will determine need for adjuvant therapy.","timestamp":"Today, 09:00","severity":"info","sources":["Pathology","Surgery Note"]}]',
'[{"id":"tr-ll-1","label":"Pain Score","value":"3/10","direction":"down","change":"↓ improving"},{"id":"tr-ll-2","label":"JP Drain","value":"Minimal","direction":"down"},{"id":"tr-ll-3","label":"Diet","value":"Clear liquids","direction":"up","change":"Advancing"},{"id":"tr-ll-4","label":"Ambulation","value":"2 laps","direction":"up"}]'),

-- Christopher Young (Surgical, Appendicitis)
('6cfb3b21-9afb-449c-8e03-c00100fca84f',
'[{"id":"ins-cy-1","title":"Perforated Appendicitis — Monitoring for Abscess","description":"POD 0 with expected low-grade fever. WBC trending down. If fever persists beyond POD 2, CT recommended to rule out intra-abdominal abscess.","timestamp":"Today, 12:00","severity":"warning","sources":["Operative Note","Lab Trend","Surgical Protocol"]},{"id":"ins-cy-2","title":"IV Antibiotics Course","description":"5-day course of ceftriaxone + metronidazole per protocol for perforated appendicitis. Will transition to PO on discharge.","timestamp":"Today, 08:00","severity":"info","sources":["Pharmacy","Surgical Protocol"]}]',
'[{"id":"tr-cy-1","label":"Temperature","value":"38.1°C","direction":"stable","change":"Expected POD 0"},{"id":"tr-cy-2","label":"WBC","value":"16.4 K","direction":"down","change":"↓ from 22.1"},{"id":"tr-cy-3","label":"Drain Output","value":"50 mL","direction":"stable"},{"id":"tr-cy-4","label":"Pain","value":"4/10","direction":"stable"}]'),

-- Matthew Adams (Surgical, SBO)
('029266f0-acc4-45df-96b3-a47bc96fdf6e',
'[{"id":"ins-ma-1","title":"SBO Showing Early Resolution","description":"NGT output decreasing (800 → 300mL/shift). Abdomen less distended. Gastrografin challenge planned today. No surgical indicators at this time.","timestamp":"Today, 07:00","severity":"info","sources":["NGT Output Log","Abdominal Exam","KUB"]},{"id":"ins-ma-2","title":"Surgical Backup Plan","description":"If no resolution by day 3, operative intervention (lysis of adhesions) will be recommended. Patient counseled and consented.","timestamp":"Yesterday, 16:00","severity":"warning","sources":["Surgical Note","Consent"]}]',
'[{"id":"tr-ma-1","label":"NGT Output","value":"300 mL/8h","direction":"down","change":"↓ from 800"},{"id":"tr-ma-2","label":"Distension","value":"Mild","direction":"down","change":"↓ improving"},{"id":"tr-ma-3","label":"Lactate","value":"0.9","direction":"stable","change":"No ischemia"},{"id":"tr-ma-4","label":"Pain","value":"4/10","direction":"down","change":"↓ from 7/10"}]'),

-- David Walker (Rehab, CVA)
('88ff7bd5-e64b-4603-98ec-5b2d4fd32136',
'[{"id":"ins-dw2-1","title":"Functional Gains in Rehab","description":"FIM score improved from 45 to 62. Left UE strength improving (2/5 → 3/5). Ambulating 50 feet with walker and minimal assist.","timestamp":"Today, 14:00","severity":"success","sources":["PT Evaluation","OT Evaluation","FIM Tracking"]}]',
'[{"id":"tr-dw2-1","label":"FIM Score","value":"62","direction":"up","change":"↑ from 45"},{"id":"tr-dw2-2","label":"L UE Strength","value":"3/5","direction":"up","change":"↑ from 2/5"},{"id":"tr-dw2-3","label":"Ambulation","value":"50 ft","direction":"up"},{"id":"tr-dw2-4","label":"Swallow","value":"Modified liquids","direction":"stable"}]'),

-- Daniel Wright (Rehab, SCI)
('184b277c-2e03-4b7f-9741-2bc27694fea8',
'[{"id":"ins-dnw-1","title":"Gradual Motor Recovery","description":"Bilateral LE strength 2-3/5, improving from admission. Transfers with moderate assist. Neuropathic pain managed with gabapentin.","timestamp":"Today, 10:00","severity":"info","sources":["PT Evaluation","Neurology Note","Pain Assessment"]}]',
'[{"id":"tr-dnw-1","label":"FIM Score","value":"58","direction":"up"},{"id":"tr-dnw-2","label":"LE Strength","value":"2-3/5","direction":"up"},{"id":"tr-dnw-3","label":"Bladder Residuals","value":"100-150 mL","direction":"stable"},{"id":"tr-dnw-4","label":"Skin Integrity","value":"Intact","direction":"stable"}]'),

-- Nancy Hall (LTC, Dementia)
('a1ba7991-4565-47a9-a884-705e81de436f',
'[{"id":"ins-nh-1","title":"Acute Cognitive Decline","description":"More confused than baseline over 2 days with decreased oral intake. Mild AKI likely pre-renal. Dehydration most likely cause.","timestamp":"Today, 09:00","severity":"warning","sources":["Nursing Assessment","BMP","UA Results"]},{"id":"ins-nh-2","title":"Medication Hold","description":"Metformin held due to elevated creatinine (1.6, baseline 1.4). Will reassess after rehydration.","timestamp":"Today, 09:30","severity":"info","sources":["Pharmacy Review","BMP"]}]',
'[{"id":"tr-nh-1","label":"Creatinine","value":"1.6","direction":"up","change":"↑ from 1.4"},{"id":"tr-nh-2","label":"Sodium","value":"132","direction":"down","change":"↓ from 136"},{"id":"tr-nh-3","label":"Weight","value":"52 kg","direction":"down","change":"↓ 1kg/month"},{"id":"tr-nh-4","label":"Oral Intake","value":"Poor","direction":"down"}]'),

-- Karen Scott (LTC, Parkinson)
('9ba6d176-f93a-4fd6-b28a-230bcf252eab',
'[{"id":"ins-ks-1","title":"Fall Risk — Orthostatic Hypotension","description":"2 falls this week. Orthostatic BP drop confirmed (142/78 → 108/62). Contributing to fall risk along with freezing gait episodes.","timestamp":"Today, 08:00","severity":"warning","sources":["Nursing Incident Reports","Vital Signs","PT Assessment"]},{"id":"ins-ks-2","title":"Neurology Consult Recommended","description":"Motor fluctuations and REM sleep behavior disorder suggest medication adjustment needed. L-dopa timing may be suboptimal.","timestamp":"Today, 09:00","severity":"info","sources":["Medication Review","Sleep Assessment"]}]',
'[{"id":"tr-ks-1","label":"Falls (7d)","value":"2","direction":"up","change":"↑ increased"},{"id":"tr-ks-2","label":"Orthostatic Drop","value":"34 mmHg","direction":"up"},{"id":"tr-ks-3","label":"MMSE","value":"24/30","direction":"stable"},{"id":"tr-ks-4","label":"Gait","value":"Shuffling/Freezing","direction":"down"}]');
